version: "3.8"

services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kaddem

    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  app-kaddem:
    depends_on:
      - mysqldb
    image: salma508/kaddem-app:latest
    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: |
        {
              "spring.datasource.url": "jdbc:mysql://mysqldb:3306/kaddem?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false",
              "spring.datasource.username": "root",
              "spring.datasource.password": "root",
              "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL8Dialect",
              "spring.jpa.hibernate.ddl-auto": "update"
        }
    stdin_open: true
    tty: true

  fangular-app:
    image: salma508/kaddem-frontend:latest
    ports:
      - "80:80"  
    restart: always
    depends_on:
      - app-kaddem
volumes:
  db:
  
