version: "3.8"

services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kaddem
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  backend:
    image: jassem145/kaddem-app:latest
    container_name: backend
    depends_on:
      - mysqldb
    ports:
      - "8089:8089"
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/kaddem?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
    stdin_open: true
    tty: true

  frontend:
    image: jassem145/kaddem-frontend:latest
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: always

volumes:
  db:
